# Generated by Django 4.2.3 on 2023-08-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=40)),
                ("Last_name", models.CharField(max_length=40)),
                ("age", models.IntegerField()),
                ("email", models.EmailField(max_length=255)),
                ("disease", models.CharField(max_length=2000)),
            ],
        ),
    ]
