# Generated by Django 4.2.3 on 2023-08-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("age", models.IntegerField()),
                ("city", models.CharField(max_length=40)),
                ("subject", models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name="App",
        ),
    ]
